import { Currency } from "../../../domain/enums";

export const processPspSchema = {
  summary: "Process Payment",
  description: "Processes a payment transaction on the PSP side.",
  tags: ["PSP Transactions"],
  body: {
    type: "object",
    required: ["amount", "currency", "cardNumber", "cvv", "cardExpiry"],
    properties: {
      transactionId: { type: "string", description: "Transaction ID From DB" },
      internalId: {
        type: "string",
        description: "Internal Transaction ID Generated By Payment Service",
      },
      amount: {
        type: "integer",
        minimum: 1,
        description: "Amount in smallest currency unit",
      },
      currency: {
        type: "string",
        enum: Object.values(Currency),
        minLength: 3,
        maxLength: 3,
        description: "ISO 4217 Currency Code",
      },
      cardNumber: {
        type: "string",
        minLength: 16,
        maxLength: 16,
        description: "16-digit card number",
      },
      cardExpiry: { type: "string", description: "Card expiry date (MM/YY)" },
      cvv: {
        type: "string",
        minLength: 3,
        maxLength: 4,
        description: "Card security code",
      },
      orderId: { type: "string", description: "Order ID" },
      callbackUrl: {
        type: "string",
        description: "URL to call back with valid 3DS token",
      },
      failureUrl: {
        type: "string",
        description: "URL to redirect to on failure",
      },
    },
  },
  response: {
    200: {
      description: "Payment processed successfully",
      type: "object",
      properties: {
        status: { type: "string" },
        transactionId: { type: "string" },
        redirectUrl: { type: "string" },
      },
    },
  },
};

export const get3dsSchema = {
  summary: "3DS Authentication Page",
  description:
    "Returns the 3DS authentication HTML page for a specific transaction.",
  tags: ["PSP Transactions"],
  params: {
    type: "object",
    properties: {
      id: { type: "string", description: "Transaction ID" },
    },
  },
  response: {
    200: {
      description: "3DS HTML Page",
      type: "string",
      content: {
        "text/html": {
          schema: {
            type: "string",
          },
        },
      },
    },
  },
};

export const paymentCompleteSchema = {
  summary: "Complete Payment",
  description: "Completes the payment process after 3DS authentication.",
  tags: ["PSP Transactions"],
  body: {
    type: "object",
    required: ["transactionId"],
    properties: {
      transactionId: { type: "string", description: "Transaction ID" },
    },
  },
  response: {
    200: {
      description: "Payment Completion Page",
      type: "string",
      content: {
        "text/html": {
          schema: {
            type: "string",
          },
        },
      },
    },
  },
};

export const paymentCancelSchema = {
  summary: "Cancel Payment",
  description: "Cancels the payment process.",
  tags: ["PSP Transactions"],
  body: {
    type: "object",
    required: ["transactionId"],
    properties: {
      transactionId: { type: "string" },
    },
  },
  response: {
    200: {
      type: "object",
      properties: {
        redirectUrl: { type: "string" },
      },
    },
  },
};
